//! Which data centre a Telegram address belongs to.
//!
//! Layer 20. Ports `_TG_EXACT_TARGETS`, `_domain_dc`, `_target_dc_hint`,
//! `_likely_media_target` and `_preferred_ws_target`.
//!
//! Everything downstream is keyed by the DC this produces — the native health
//! table, the first-byte circuit, the Worker domain, the media bar. Getting it
//! wrong does not fail; it files a working route under the wrong bucket and goes
//! on doing so.
//!
//! **The table below was generated by executing the Python**, not transcribed.
//!
//! **`kws203` is dead code in the original, and reproduced as such.**
//! `_domain_dc` tests `kws2` before `kws203`, so a `kws203.*` name answers
//! **2**, never 203. Harmless — 203 folds to 2 everywhere else, and
//! `_ws_domains` never builds such a name — but the port matches the behaviour
//! rather than the apparent intent, and a test pins it.

use crate::egress::Dc;
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr};

/// `(address, dc, is_media)` — the addresses Telegram publishes, verbatim.
pub const EXACT_TARGETS: &[(&str, u16, bool)] = &[
    ("149.154.175.50", 1, false),
    ("149.154.175.51", 1, false),
    ("149.154.175.53", 1, false),
    ("149.154.175.54", 1, false),
    ("149.154.175.55", 1, false),
    ("149.154.175.59", 1, false),
    ("149.154.175.52", 1, true),
    ("149.154.167.35", 2, false),
    ("149.154.167.36", 2, false),
    ("149.154.167.41", 2, false),
    ("149.154.167.50", 2, false),
    ("149.154.167.51", 2, false),
    ("149.154.167.220", 2, false),
    ("95.161.76.100", 2, false),
    ("149.154.162.123", 2, true),
    ("149.154.167.151", 2, true),
    ("149.154.167.222", 2, true),
    ("149.154.167.223", 2, true),
    ("149.154.167.99", 2, true),
    ("149.154.175.100", 3, false),
    ("149.154.175.101", 3, false),
    ("149.154.175.102", 3, true),
    ("149.154.164.250", 4, true),
    ("149.154.165.111", 4, true),
    ("149.154.166.120", 4, true),
    ("149.154.166.121", 4, true),
    ("149.154.167.91", 4, false),
    ("149.154.167.92", 4, false),
    ("149.154.167.118", 4, true),
    ("91.108.56.100", 5, false),
    ("91.108.56.101", 5, false),
    ("91.108.56.102", 5, true),
    ("91.108.56.116", 5, false),
    ("91.108.56.126", 5, false),
    ("91.108.56.128", 5, true),
    ("91.108.56.123", 5, true),
    ("91.108.56.151", 5, true),
    ("149.154.171.5", 5, false),
    ("91.105.192.100", 203, false),
];

fn exact(ip: &str) -> Option<(u16, bool)> {
    EXACT_TARGETS.iter().find(|(addr, _, _)| *addr == ip).map(|(_, dc, media)| (*dc, *media))
}

/// The DC a Worker or Telegram-Web hostname names.
pub fn domain_dc(domain: &str) -> Option<Dc> {
    let d = domain.trim().to_ascii_lowercase();
    let number = if d.starts_with("pluto") || d.starts_with("kws1") {
        1
    } else if d.starts_with("venus") || d.starts_with("kws2") {
        2
    } else if d.starts_with("aurora") || d.starts_with("kws3") {
        3
    } else if d.starts_with("vesta") || d.starts_with("kws4") {
        4
    } else if d.starts_with("flora") || d.starts_with("kws5") {
        5
    } else if d.starts_with("kws203") {
        // Unreachable: `kws2` above already claimed it. Kept so the shape of the
        // original stays visible, and asserted dead by a test.
        203
    } else {
        0
    };
    Dc::new(number)
}

fn in_v4_network(addr: Ipv4Addr, base: [u8; 4], prefix: u32) -> bool {
    let mask = if prefix == 0 { 0 } else { u32::MAX << (32 - prefix) };
    (u32::from(addr) & mask) == (u32::from(Ipv4Addr::from(base)) & mask)
}

fn in_v6_prefix64(addr: Ipv6Addr, base: [u16; 4]) -> bool {
    addr.segments()[..4] == base
}

/// The DC an address belongs to, or `None` when nothing here recognises it.
pub fn target_dc_hint(target_ip: &str, media: bool) -> Option<Dc> {
    let ip = target_ip.trim().to_ascii_lowercase();
    if ip.is_empty() {
        return None;
    }
    if let Some((dc, _)) = exact(&ip) {
        return Dc::new(dc);
    }
    let number = match ip.as_str() {
        "173.239.243.185" => 5,
        "5.28.195.2" => 4,
        "149.154.167.220" => {
            if media {
                4
            } else {
                2
            }
        }
        "149.154.167.92" | "149.154.167.255" => 4,
        "149.154.167.50" | "149.154.167.41" => 2,
        _ => 0,
    };
    if number != 0 {
        return Dc::new(number);
    }

    let addr: IpAddr = ip.parse().ok()?;
    let number = match addr {
        IpAddr::V4(v4) => {
            if in_v4_network(v4, [91, 108, 56, 0], 22) || in_v4_network(v4, [149, 154, 171, 0], 24) {
                5
            } else if v4 == Ipv4Addr::new(149, 154, 167, 91) {
                4
            } else if in_v4_network(v4, [149, 154, 167, 0], 24) {
                2
            } else if in_v4_network(v4, [149, 154, 175, 48], 28) {
                1
            } else if v4 == Ipv4Addr::new(149, 154, 175, 100) {
                3
            } else if v4 == Ipv4Addr::new(91, 105, 192, 100) {
                203
            } else {
                0
            }
        }
        IpAddr::V6(v6) => {
            if in_v6_prefix64(v6, [0x2001, 0x067c, 0x04e8, 0xf002]) {
                2
            } else if in_v6_prefix64(v6, [0x2001, 0x067c, 0x04e8, 0xf004]) {
                4
            } else if in_v6_prefix64(v6, [0x2001, 0x0b28, 0xf23f, 0xf005]) {
                5
            } else {
                0
            }
        }
    };
    Dc::new(number)
}

/// Whether this session is likely to be carrying media.
///
/// Ports 7300-7310 are never media whatever else says: that range is Telegram's
/// own non-media transport, and reading it as media would put a plain session
/// behind the 4 KiB progress bar.
pub fn likely_media_target(target_ip: &str, port: u16, dc: Option<Dc>) -> bool {
    let ip = target_ip.trim().to_ascii_lowercase();
    if let Some((_, media)) = exact(&ip) {
        return media;
    }
    if matches!(
        ip.as_str(),
        "5.28.195.2" | "149.154.167.91" | "149.154.167.92" | "149.154.167.99" | "149.154.167.255"
    ) {
        return true;
    }
    if (7300..=7310).contains(&port) {
        return false;
    }
    dc.map(Dc::get) == Some(4) && (port == 80 || port == 443)
}

/// The address a WSS tunnel should be pointed at.
pub fn preferred_ws_target(target_ip: &str, dc: Option<Dc>, media: bool) -> String {
    let ip = target_ip.trim().to_string();
    match dc.map(Dc::get) {
        Some(2) => "149.154.167.220".to_string(),
        Some(4) if media || matches!(ip.as_str(), "5.28.195.2" | "149.154.167.91" | "149.154.167.255") => {
            "149.154.167.220".to_string()
        }
        _ => ip,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_exact_table_came_over_whole() {
        assert_eq!(EXACT_TARGETS.len(), 39);
        assert!(EXACT_TARGETS.iter().any(|(_, _, media)| *media), "media addresses exist");
        assert!(EXACT_TARGETS.iter().any(|(_, _, media)| !*media));
        for (ip, dc, _) in EXACT_TARGETS {
            assert!(ip.parse::<IpAddr>().is_ok(), "{ip}");
            assert!((1..=203).contains(dc), "{ip} -> {dc}");
        }
    }

    #[test]
    fn kws203_answers_two_because_kws2_gets_there_first() {
        assert_eq!(domain_dc("kws203.nova-app.eu").map(Dc::get), Some(2));
    }

    #[test]
    fn the_seven_three_hundreds_are_never_media() {
        for port in [7300u16, 7305, 7310] {
            assert!(!likely_media_target("1.2.3.4", port, Dc::new(4)), "{port}");
        }
        assert!(likely_media_target("1.2.3.4", 443, Dc::new(4)), "but 443 on DC4 is");
        assert!(!likely_media_target("1.2.3.4", 443, Dc::new(2)), "and DC2 is not");
    }

    #[test]
    fn the_exact_table_shadows_three_branches_that_look_live_and_are_not() {
        // Found by mutation: removing any of the three below changed nothing,
        // because `exact()` answers first. Pinned so a future reader does not
        // "fix" them by reordering, which would change behaviour.

        // 1. `149.154.167.220`'s media split. The special case says DC4 for
        //    media, the exact table says (2, non-media) flatly, and the table
        //    wins — so media never gets DC4 for this address.
        assert_eq!(target_dc_hint("149.154.167.220", true).map(Dc::get), Some(2));
        assert_eq!(target_dc_hint("149.154.167.220", false).map(Dc::get), Some(2));

        // 2. The `.91` special case in the range walk. Shadowed the same way.
        assert_eq!(target_dc_hint("149.154.167.91", false).map(Dc::get), Some(4));

        // 3. **A contradiction, not just a shadow.** `_likely_media_target`
        //    lists `.91` and `.92` among its media addresses, and the exact
        //    table lists both as *non*-media. The table wins, so they are
        //    treated as non-media. One of the two statements is wrong and which
        //    one is a question for a measurement, not for a port.
        assert!(!likely_media_target("149.154.167.91", 443, Dc::new(4)));
        assert!(!likely_media_target("149.154.167.92", 443, Dc::new(4)));
        // The other three in that set are not in the exact table, so they do
        // count as media.
        for ip in ["5.28.195.2", "149.154.167.255"] {
            assert!(likely_media_target(ip, 443, Dc::new(4)), "{ip}");
        }
        // `.99` is in the table *as* media, so both agree.
        assert!(likely_media_target("149.154.167.99", 443, Dc::new(2)));
    }

    #[test]
    fn the_seven_three_hundred_guard_cannot_change_an_answer() {
        // Also found by mutation. Removing it changes nothing: the line after it
        // returns `dc == 4 && (port == 80 || port == 443)`, and no port in
        // 7300..=7310 is 80 or 443. Kept because the original has it and it
        // states an intent worth keeping visible, but it decides nothing.
        for port in 7300u16..=7310 {
            assert!(!likely_media_target("1.2.3.4", port, Dc::new(4)), "with the guard: {port}");
            // The same answer the fall-through would give on its own.
            assert!(port != 80 && port != 443);
        }
    }

    #[test]
    fn an_unknown_address_belongs_to_no_data_centre() {
        assert_eq!(target_dc_hint("8.8.8.8", false), None);
        assert_eq!(target_dc_hint("", false), None);
        assert_eq!(target_dc_hint("not-an-ip", false), None);
        assert_eq!(domain_dc("example.test"), None);
    }
}
